### PR TITLE
Some fixes

### PR DESCRIPTION
**Pull request by tiennou**
This goes *after* quicksilver/Quicksilver#2348 is merged.

Feel free to cherry-pick the other fix, as it's pretty bad actually. We'll copy the whole DB file on each scan, once for each object source.

### CODE REVIEW

**Comment by skurfer** [comment]
The `Info.plist` should be updated to require 401F.

**Comment by skurfer** [comment]
Two problems with this.

1. The history parser needs FMDB, but can’t find it. Moving the FMDB import from `QSGoogleChromeDatabaseManager.m` to `QSGoogleChromeDatabaseManager.h` fixes that.
2. The auto-generated header file for Scripting Bridge is broken. (The protocol it uses has a space in its name.) What do you think about just generating the header, fixing it, and including it in the project as-is instead of having it built from the app each time? (We could also remove the app at that point.)

I can do both if you agree.

**Comment by tiennou** [comment]
I was *just* looking at it 😆 . Yes, feel free to change that (though I remember it was building, since I debugged it. Weird). Also, you should be able to split the PR in 2 parts so we don't have a dependency on quicksilver/Quicksilver#2348, so "older" versions can still get the fix. It's just that I started by killing the FMDB dependency before the OMG moment happened.

I haven't really tested it that hard though, just making sure that the file copy part was killed. For the record, the "unix-none" documentation is [here](https://sqlite.org/vfs.html), it should allow us to open readonly without using any locks, which should not cause Chrome/Safari to bark because its own db is locked (at least that's the theory).

**Comment by skurfer** [comment]
OK. I’ll put the read-only fix and the SB changes on master and release that. We’ll get conflicts here after, but not a big deal.

**Comment by skurfer** [comment]
Redoing the work is probably easier than rebasing at this point. I’ll take care of it.

**Pull request closed without merging**
